pub mod anime;
pub mod books;
pub mod comics;
pub mod light_novels;
pub mod manga;
pub mod meta;
pub mod movies;
pub mod news;
pub mod others;

pub use anime::*;
pub use books::*;
pub use comics::*;
pub use light_novels::*;
pub use manga::*;
pub use meta::*;
pub use movies::*;
pub use news::*;
pub use others::*;
