contact_links:
  - name: 🙋 Question
    url: https://discord.gg/qTPfvMxzNH
    about: Ask your question or suggestion in Discord server

  - name: 🍔 Providers list
    url: https://consumet.org/extensions/list/
    about: A list of the available providers

  - name: 🌐 Rest-API reference
    url: https://docs.consumet.org
    about: A reference of the Consumet Rest-API documentation
